### ISSUE TITLE
CoreServicesUIAgent blocks UITests with system alert

### ISSUE THREAD

**Issue by sparta-developers** [sparta-science/connect#39]
`CoreServicesUIAgent` alert:
<img width="255" alt="Screen Shot 2020-07-13 at 9 43 06 PM" src="https://user-images.githubusercontent.com/31809836/87387166-febed500-c556-11ea-91b7-49d4520d4336.png">

“SpartaConnectRelease” is an app downloaded from the Internet. Are you sure you want to open it?

Probably related to #13 - Failed to get matching snapshots: Lost connection to the application which is confusing error caused by blocking alert.

Accessibility Inspector fields:
<img width="750" alt="Screen Shot 2020-07-13 at 9 49 16 PM" src="https://user-images.githubusercontent.com/31809836/87387170-03838900-c557-11ea-8d1f-d8fa3ad1415c.png">

**Comment by paulz** [comment]
already fixed by dismissing alert, https://github.com/sparta-science/connect/blob/a779563c2326e220b045802240ebb1a9c2bc4f15/UITests/UpdateAppTest.swift#L59

RareEventMonitor.log(.uiagentWarning) does not seem to happen for the last 300 runs
