### ISSUE TITLE
Application fails to start up due to exception stopping vernal falls

### ISSUE THREAD

**Issue by sparta-developers** [sparta-science/connect#44]
The last time you opened SpartaConnect, it unexpectedly quit while reopening windows. Do you want to try to reopen its windows again?

If you choose not to reopen windows, you may have to open and position the windows yourself. 

[Don’t Reopen] [Reopen]

<img width="309" alt="Screen Shot 2020-08-03 at 11 54 23 AM" src="https://user-images.githubusercontent.com/31809836/89217609-51e9dd80-d581-11ea-9900-3a4029566120.png">

**Comment by paulz** [comment]
The above happened during development when we tried to raise exception while application was starting.

There is no point of opening without opening windows, as our app is single window app.

We might consider setting `NSQuitAlwaysKeepsWindows` to true for the UI tests if they encounter crashes.
see discussion at https://developer.apple.com/forums/thread/89863
