### ISSUE TITLE
Starting app on BigSur fails with "Failed with exit code: 5"

### ISSUE THREAD

**Issue by sparta-developers** [sparta-science/connect#47]
When starting the app from connected state on BigSur:

> 2020-08-05 11:07:59.488421-0700 launchctl[26518:4110910] [All] launchctl bootstrap: /bin/launchctl bootstrap gui/501 sparta_science.vernal_falls.plist
> Bootstrap failed: 5: Input/output error
> 

<img width="250" alt="Screen Shot 2020-08-05 at 11 08 11 AM" src="https://user-images.githubusercontent.com/31809836/89452545-aec8cd80-d712-11ea-84e6-a110d7149eb9.png">

and service still starts successfully

**Comment by sparta-developers** [comment]
seems to be cause by `StandardOutPath` and `StandardErrorPath` values in the plist. As we changed values to /tmp/somelog.log it worked.

**Comment by sparta-developers** [comment]
we see logs are not written when this error happens.

**Comment by kellyfelkins** [comment]
Error 5: EIO

Kicking the can down the road as logs are now working on Big Sur due to this commit. Error is still popping up but user can ignore and continue.

https://github.com/sparta-science/connect/commit/b27f08c148a517dc7b08c4dff7f9ba49976caf0b

**Comment by paulz** [comment]
Try splitting stderr and stdout

**Comment by paulz** [comment]
Looks like it's caused by log files being locked by previous instance that is in the process of exiting.

One solution could be wait for the previous instance to exit by polling the `launchctl blame` until service is no longer running.

This is better done in a shell script which could evolve later to enable log rotation.

**Comment by sparta-developers** [comment]
on BigSur beta - 11.0 Beta (20A5343i):

subsequent launches of the `launchctl` service cause this error:
```
launchctl bootstrap gui/501 sparta_science.vernal_falls.plist

Bootstrap failed: 5: Input/output error
```
